< 제2유형 : 데이터분석 >

# 분류

## decisionTree

### 연습 : iris

In [1]:
import pandas as pd
import numpy as np
import sklearn

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../Dataset/iris.csv")

In [3]:
df['species'].replace({'setosa':0, 'versicolor':1, 'virginica':2}, inplace=True)
df

/var/folders/j5/2p33mq0s3pbg5spm_mqqxgw00000gn/T/ipykernel_67582/2210977312.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['species'].replace({'setosa':0, 'versicolor':1, 'virginica':2}, inplace=True)
/var/folders/j5/2p33mq0s3pbg5spm_mqqxgw00000gn/T/ipykernel_67582/2210977312.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('fut

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [4]:
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)

In [5]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(120, 4) (30, 4) (120,) (30,)


In [6]:
dt = DecisionTreeClassifier(random_state=11)
dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [7]:
pred = dt.predict(X_test)

In [8]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, pred)
print(acc)

0.9333333333333333


In [9]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[ 9,  0,  0],
       [ 0, 10,  0],
       [ 0,  2,  9]])

In [10]:
from sklearn.metrics import classification_report
rpt = classification_report(y_test, pred)
print(rpt)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.83      1.00      0.91        10
           2       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30



### 연습 : titanic

In [38]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

df = pd.read_csv("../Dataset/titanic.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
d_mean = df['Age'].mean()
df['Age'] = df['Age'].fillna(d_mean)

d_mode = df['Embarked'].mode()[0]
df['Embarked'] = df['Embarked'].fillna(d_mode)

from sklearn.preprocessing import LabelEncoder
df['Sex'] = LabelEncoder().fit_transform(df['Sex'])
df['Embarked'] = LabelEncoder().fit_transform(df['Embarked'])

df['FamilySize'] = df['SibSp'] + df['Parch']

In [ ]:
X = df[['Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'FamilySize']]
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2, random_state=11)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

dt = DecisionTreeClassifier(random_state=11)
dt.fit(X_train, y_train)

pred = dt.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

acc = accuracy_score(y_test, pred)
print(acc)

rpt = classification_report(y_test, pred)
print(rpt)

0.7447405329593267


## knn

### 연습 : iris

In [31]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv("../Dataset/iris.csv")
scaler = MinMaxScaler()
df[['sepal_length']] = scaler.fit_transform(df[['sepal_length']])
df[['sepal_width']] = scaler.fit_transform(df[['sepal_width']])
df[['petal_length']] = scaler.fit_transform(df[['petal_length']])
df[['petal_width']] = scaler.fit_transform(df[['petal_width']])

In [32]:
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)

In [33]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

pred = knn.predict(X_test)

In [35]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

acc = accuracy_score(y_test, pred)
mat = confusion_matrix(y_test, pred)
rpt = classification_report(y_test, pred)
print(f"{acc}\n\n{mat}\n\n{rpt}")

0.9333333333333333

[[ 9  0  0]
 [ 0 10  0]
 [ 0  2  9]]

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         9
  versicolor       0.83      1.00      0.91        10
   virginica       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30



### 연습 : titanic

In [40]:
import numpy as np
import pandas as pd
import sklearn

df = pd.read_csv("../Dataset/titanic.csv")

In [41]:
d_mean = df['Age'].mean()
df['Age'] = df['Age'].fillna(d_mean)

d_mode = df['Embarked'].mode()[0]
df['Embarked'] = df['Embarked'].fillna(d_mode)

from sklearn.preprocessing import LabelEncoder
df['Sex'] = LabelEncoder().fit_transform(df['Sex'])
df['Embarked'] = LabelEncoder().fit_transform(df['Embarked'])

df['FamilySize'] = df['SibSp'] + df['Parch']

In [42]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

knn.fit(X_train, y_train)
pred = knn.predict(X_test)

In [43]:
from sklearn.metrics import confusion_matrix, classification_report

mat = confusion_matrix(y_test, pred)
rpt = classification_report(y_test, pred)
print(f"{mat}\n\n{rpt}")

[[ 9  0  0]
 [ 0 10  0]
 [ 0  2  9]]

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         9
  versicolor       0.83      1.00      0.91        10
   virginica       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30



## SVM (titanic)

In [51]:
import numpy as np
import pandas as pd
import sklearn

from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv("../Dataset/titanic.csv")

In [52]:
d_mean = df['Age'].mean()
df['Age'] = df['Age'].fillna(d_mean)

d_mode = df['Embarked'].mode()[0]
df['Embarked'] = df['Embarked'].fillna(d_mode)

df['FamilySize'] = df['SibSp'] + df['Parch']

onehot_sex = pd.get_dummies(df['Sex'])
df = pd.concat([df, onehot_sex], axis=1)

onehot_embarked = pd.get_dummies(df['Embarked'])
df = pd.concat([df, onehot_embarked], axis=1)

In [53]:
X = df[['Pclass', 'Age', 'Fare', 'FamilySize', 'female', 'male', 'C', 'Q', 'S']]
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)

In [54]:
svm = svm.SVC(kernel='rbf')
svm.fit(X_train, y_train)

pred = svm.predict(X_test)
acc = accuracy_score(y_test, pred)
mat = confusion_matrix(y_test, pred)
rpt = classification_report(y_test, pred)

print(f"{acc}\n\n{mat}\n\n{rpt}")

0.7201492537313433

[[167   7]
 [ 68  26]]

              precision    recall  f1-score   support

           0       0.71      0.96      0.82       174
           1       0.79      0.28      0.41        94

    accuracy                           0.72       268
   macro avg       0.75      0.62      0.61       268
weighted avg       0.74      0.72      0.67       268



## 로지스틱 (titanic)

In [4]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

df = pd.read_csv("../Dataset/iris.csv")

In [6]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['sepal_length']] = scaler.fit_transform(df[['sepal_length']])
df[['sepal_width']] = scaler.fit_transform(df[['sepal_width']])
df[['petal_length']] = scaler.fit_transform(df[['petal_length']])
df[['petal_width']] = scaler.fit_transform(df[['petal_width']])

X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)

In [7]:
logistic = LogisticRegression()
logistic.fit(X_train, y_train)

pred = logistic.predict(X_test)

In [8]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, pred))

0.8333333333333334


## 랜덤 포레스트

In [9]:
import pandas as pd
import numpy as np
import sklearn

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

df = pd.read_csv("../Dataset/titanic.csv")

In [11]:
d_mean = df['Age'].mean()
df['Age'] = df['Age'].fillna(d_mean)

d_mode = df['Embarked'].mode()[0]
df['Embarked'] = df['Embarked'].fillna(d_mode)

from sklearn.preprocessing import LabelEncoder
df['Sex'] = LabelEncoder().fit_transform(df['Sex'])
df['Embarked'] = LabelEncoder().fit_transform(df['Embarked'])

df['FamilySize'] = df['SibSp'] + df['Parch']

X = df[['Pclass', 'Sex', 'Age', 'Fare', 'Embarked', 'FamilySize']]
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)

In [12]:
rf = RandomForestClassifier(n_estimators=50, max_depth=3, random_state=20)
rf.fit(X_train, y_train)

pred = rf.predict(X_test)

from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, pred)
print(acc)

0.8603351955307262


# 회귀

## 단순회귀

In [13]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [14]:
df = pd.read_csv("../Dataset/auto-mpg.csv")
df = df.dropna(axis=0)

X = df[['horsepower']]
y = df['mpg']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)

In [ ]:
lr = LinearRegression()
lr.fit(X_train, y_train)

print(f"기울기 : {lr.coef_}, y절편 : {lr.intercept_}")
pred = lr.predict(X_test)
print(f"{r2_score(y_test, pred)}")

기울기 : [-0.15331988] / y절편 : 39.46988560736385
0.5780544812335405


## 다중회귀

In [27]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

df = pd.read_csv("../Dataset/housing.csv")

In [28]:
df = df.dropna(axis = 0)
df = df.drop("ocean_proximity", axis=1)
corr = df.corr(method = "pearson")
print(corr)

                    longitude  latitude  ...  median_income  median_house_value
longitude            1.000000 -0.924616  ...      -0.015550           -0.045398
latitude            -0.924616  1.000000  ...      -0.079626           -0.144638
housing_median_age  -0.109357  0.011899  ...      -0.118278            0.106432
total_rooms          0.045480 -0.036667  ...       0.197882            0.133294
total_bedrooms       0.069608 -0.066983  ...      -0.007723            0.049686
population           0.100270 -0.108997  ...       0.005087           -0.025300
households           0.056513 -0.071774  ...       0.013434            0.064894
median_income       -0.015550 -0.079626  ...       1.000000            0.688355
median_house_value  -0.045398 -0.144638  ...       0.688355            1.000000

[9 rows x 9 columns]


In [29]:
X = df.drop("median_house_value", axis = 1)
y = df['median_house_value']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [34]:
lr = LinearRegression()
lr.fit(X_train, y_train)
print(f"기울기 : {lr.coef_}, y절편 : {lr.intercept_}", end='\n\n')

pred = lr.predict(X_test)
print(f"r2_score : {r2_score(y_test, pred)}")

기울기 : [-4.21262308e+04 -4.20623763e+04  1.18784999e+03 -8.57874086e+00
  1.18123421e+02 -3.55751755e+01  3.73676747e+01  4.03297253e+04], y절편 : -3530241.307797076

r2_score : 0.644513029108235


## 의사결정나무

In [36]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

df = pd.read_csv("../Dataset/housing.csv")

In [37]:
df = df.dropna(axis = 0)
df = df.drop("ocean_proximity", axis=1)
corr = df.corr(method = "pearson")
print(corr)

                    longitude  latitude  ...  median_income  median_house_value
longitude            1.000000 -0.924616  ...      -0.015550           -0.045398
latitude            -0.924616  1.000000  ...      -0.079626           -0.144638
housing_median_age  -0.109357  0.011899  ...      -0.118278            0.106432
total_rooms          0.045480 -0.036667  ...       0.197882            0.133294
total_bedrooms       0.069608 -0.066983  ...      -0.007723            0.049686
population           0.100270 -0.108997  ...       0.005087           -0.025300
households           0.056513 -0.071774  ...       0.013434            0.064894
median_income       -0.015550 -0.079626  ...       1.000000            0.688355
median_house_value  -0.045398 -0.144638  ...       0.688355            1.000000

[9 rows x 9 columns]


In [38]:
X = df.drop("median_house_value", axis = 1)
y = df['median_house_value']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42)

In [46]:
rfr = RandomForestClassifier(max_depth = 3, random_state = 42)
rfr.fit(X_train, y_train)

pred = rfr.predict(X_test)
print(f"mse = {mean_squared_error(y_test, pred)}")

mse = 99239105216.9044


# 비지도

## K-means

In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("../Dataset/iris.csv")

In [50]:
df['species'] = LabelEncoder().fit_transform(df['species'])
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

In [52]:
cluster1 = KMeans(n_clusters = 3, n_init = 10, max_iter = 500, random_state = 42)
cluster1.fit(X)

cluster_center = cluster1.cluster_centers_
cluster_prediction = cluster1.predict(X)
print(pd.DataFrame(cluster_center))
print(cluster_prediction)

          0         1         2         3
0  5.901613  2.748387  4.393548  1.433871
1  5.006000  3.428000  1.462000  0.246000
2  6.850000  3.073684  5.742105  2.071053
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 2
 2 0]


In [54]:
scope = range(1, 10)
inertias = []

for k in scope:
    model = KMeans(n_clusters = k, n_init = 10, max_iter = 500, random_state = 42)
    model.fit(X)
    inertias.append(model.inertia_)
    print(f"{k} => {inertias[k-1]}")

1 => 681.3706
2 => 152.3479517603579
3 => 78.85144142614601
4 => 57.228473214285714
5 => 46.461172672672674
6 => 39.03998724608725
7 => 34.30581529581531
8 => 30.132440554614476
9 => 28.29063524195103


## 연관분석

In [63]:
import numpy as np
import pandas as pd

from mlxtend.frequent_patterns import apriori, association_rules

In [68]:
df = pd.read_csv("../Dataset/retail_dataset.csv")

items = set()
for col in df:
    items.update(df[col].unique())

itemset = set(items)
encoding = []

for index, row in df.iterrows():
    rowset = set(row)
    labels = {}
    dismatching = list(itemset - rowset)
    matching = list(itemset.intersection(rowset))
    for i in dismatching:
        labels[i] = 0
    for j in matching:
        labels[j] = 1
    encoding.append(labels)
encoding[0]
result = pd.DataFrame(encoding)

result

Bagel  NaN  Milk  Eggs  Meat  Diaper  Wine  Cheese  Bread  Pencil
0        0    0     0     1     1       1     1       1      1       1
1        0    0     1     0     1       1     1       1      1       1
2        0    1     1     1     1       0     1       1      0       0
3        0    1     1     1     1       0     1       1      0       0
4        0    1     0     0     1       0     1       0      0       1
..     ...  ...   ...   ...   ...     ...   ...     ...    ...     ...
310      0    1     0     1     0       0     0       1      1       0
311      0    1     1     0     1       0     0       0      0       1
312      0    0     0     1     1       1     1       1      1       1
313      0    1     0     0     1       0     0       1      0       0
314      1    1     0     1     1       0     1       0      1       0

[315 rows x 10 columns]

In [69]:
result = result.drop(result.columns[0], axis=1)
result

NaN  Milk  Eggs  Meat  Diaper  Wine  Cheese  Bread  Pencil
0      0     0     1     1       1     1       1      1       1
1      0     1     0     1       1     1       1      1       1
2      1     1     1     1       0     1       1      0       0
3      1     1     1     1       0     1       1      0       0
4      1     0     0     1       0     1       0      0       1
..   ...   ...   ...   ...     ...   ...     ...    ...     ...
310    1     0     1     0       0     0       1      1       0
311    1     1     0     1       0     0       0      0       1
312    0     0     1     1       1     1       1      1       1
313    1     0     0     1       0     0       1      0       0
314    1     0     1     1       0     1       0      1       0

[315 rows x 9 columns]

In [70]:
freq_items = apriori(result, min_support=0.2, use_colnames=True)

In [73]:
rules = association_rules(freq_items, metric="confidence", min_threshold=0.6, num_itemsets=len(freq_items))
rules.head()

antecedents consequents  antecedent support  ...   jaccard  certainty  kulczynski
0      (Milk)       (nan)            0.501587  ...  0.425743  -0.410157    0.643629
1      (Eggs)       (nan)            0.438095  ...  0.346405  -0.781548    0.577489
2      (Meat)       (nan)            0.476190  ...  0.376623  -0.741463    0.598345
3    (Diaper)       (nan)            0.406349  ...  0.331126  -0.680640    0.573107
4      (Wine)       (nan)            0.438095  ...  0.320513  -1.115589    0.544801

[5 rows x 14 columns]